import type { Patient, Session, Activity, Reference, EvaluationTool } from "./types"

export const patients: Patient[] = [
  {
    id: "1",
    name: "Ana García Martínez",
    age: 8,
    email: "ana.garcia@email.com",
    phone: "+56 9 1234 5678",
    avatarUrl: "/young-girl-smiling.png",
    diagnoses: ["Dislalia", "Retraso del lenguaje"],
    dateOfBirth: "2016-03-15",
    emergencyContact: {
      name: "Carmen Martínez",
      phone: "+56 9 8765 4321",
      relationship: "Madre",
    },
    contact: {
      email: "ana.garcia@email.com",
      phone: "+56 9 1234 5678",
    },
    medicalHistory: ["Otitis recurrente", "Adenoides"],
    currentTreatments: ["Terapia del habla", "Ejercicios articulatorios"],
    progress: [
      { date: "2024-01-15", score: 45, notes: "Mejora en fonemas /r/ y /s/", area: "Articulación" },
      { date: "2024-02-15", score: 60, notes: "Mayor fluidez en conversación", area: "Fluidez" },
      { date: "2024-03-15", score: 75, notes: "Excelente progreso en /rr/", area: "Articulación" },
    ],
    notes: "Paciente muy colaborativa. Responde bien a refuerzos positivos.",
    createdAt: "2024-01-01",
    updatedAt: "2024-03-15",
  },
  {
    id: "2",
    name: "Carlos Mendoza Silva",
    age: 12,
    email: "carlos.mendoza@email.com",
    phone: "+56 9 2345 6789",
    avatarUrl: "/boy-teenager-confident.jpg",
    diagnoses: ["Tartamudez", "Ansiedad comunicativa"],
    dateOfBirth: "2012-07-22",
    emergencyContact: {
      name: "Roberto Mendoza",
      phone: "+56 9 7654 3210",
      relationship: "Padre",
    },
    contact: {
      email: "carlos.mendoza@email.com",
      phone: "+56 9 2345 6789",
    },
    medicalHistory: ["Ansiedad generalizada"],
    currentTreatments: ["Terapia de fluidez", "Técnicas de relajación"],
    progress: [
      { date: "2024-01-15", score: 30, notes: "Bloqueos frecuentes", area: "Fluidez" },
      { date: "2024-02-15", score: 50, notes: "Mejora con técnicas de respiración", area: "Fluidez" },
      { date: "2024-03-15", score: 70, notes: "Mayor confianza al hablar", area: "Confianza" },
    ],
    notes: "Requiere ambiente de confianza. Evitar presión temporal.",
    createdAt: "2024-01-01",
    updatedAt: "2024-03-15",
  },
  {
    id: "3",
    name: "Sofía Ramírez López",
    age: 6,
    email: "sofia.ramirez@email.com",
    phone: "+56 9 3456 7890",
    avatarUrl: "/little-girl-happy.jpg",
    diagnoses: ["Retraso fonológico", "Dificultades pragmáticas"],
    dateOfBirth: "2018-11-08",
    emergencyContact: {
      name: "Patricia López",
      phone: "+56 9 6543 2109",
      relationship: "Madre",
    },
    contact: {
      email: "sofia.ramirez@email.com",
      phone: "+56 9 3456 7890",
    },
    medicalHistory: ["Prematuridad leve"],
    currentTreatments: ["Estimulación fonológica", "Habilidades sociales"],
    progress: [
      { date: "2024-01-15", score: 35, notes: "Vocabulario limitado", area: "Vocabulario" },
      { date: "2024-02-15", score: 55, notes: "Incremento en palabras nuevas", area: "Vocabulario" },
      { date: "2024-03-15", score: 68, notes: "Mejor interacción social", area: "Pragmática" },
    ],
    notes: "Muy creativa. Responde bien a actividades lúdicas.",
    createdAt: "2024-01-01",
    updatedAt: "2024-03-15",
  },
]

export const sessions: Session[] = [
  {
    id: "1",
    patientId: "1",
    patientName: "Ana García Martínez",
    date: "2024-12-20",
    time: "09:00",
    duration: 45,
    type: "Terapia Individual",
    status: "Programada",
    price: 25000,
    paymentStatus: "Pendiente",
    color: "#10b981",
    objectives: ["Mejorar articulación /r/", "Ejercicios de respiración"],
    materials: ["Espejo", "Tarjetas de imágenes", "Grabadora"],
  },
  {
    id: "2",
    patientId: "2",
    patientName: "Carlos Mendoza Silva",
    date: "2024-12-20",
    time: "10:00",
    duration: 60,
    type: "Terapia de Fluidez",
    status: "Confirmada",
    price: 30000,
    paymentStatus: "Pagado",
    color: "#3b82f6",
    objectives: ["Técnicas de relajación", "Práctica de lectura fluida"],
    materials: ["Metrónomo", "Textos graduados", "Ejercicios de respiración"],
  },
  {
    id: "3",
    patientId: "3",
    patientName: "Sofía Ramírez López",
    date: "2024-12-21",
    time: "15:30",
    duration: 45,
    type: "Estimulación del Lenguaje",
    status: "Programada",
    price: 25000,
    paymentStatus: "Pendiente",
    color: "#f59e0b",
    objectives: ["Ampliar vocabulario", "Mejorar estructura sintáctica"],
    materials: ["Cuentos ilustrados", "Juegos de mesa", "Tarjetas temáticas"],
  },
]

export const activities: Activity[] = [
  {
    id: "1",
    title: "Trabalenguas Progresivos",
    description: "Serie de trabalenguas organizados por dificultad para mejorar la articulación y fluidez del habla.",
    category: "Articulación",
    difficulty: "Intermedio",
    duration: 15,
    materials: ["Tarjetas con trabalenguas", "Espejo", "Cronómetro"],
    instructions: [
      "Comenzar con trabalenguas simples",
      "Repetir lentamente 3 veces",
      "Aumentar velocidad gradualmente",
      "Observar articulación en el espejo",
    ],
    objectives: [
      "Mejorar precisión articulatoria",
      "Aumentar velocidad del habla",
      "Desarrollar conciencia fonológica",
    ],
    ageRange: "6-12 años",
    createdBy: "IA",
    tags: ["articulación", "fluidez", "fonología"],
    createdAt: "2024-12-01",
  },
  {
    id: "2",
    title: "Teatro de Emociones",
    description:
      "Actividad dramática para desarrollar habilidades pragmáticas y expresión emocional a través del lenguaje.",
    category: "Pragmática",
    difficulty: "Avanzado",
    duration: 30,
    materials: ["Máscaras de emociones", "Guiones simples", "Espacio amplio"],
    instructions: [
      "Seleccionar una emoción",
      "Practicar expresión facial y corporal",
      "Representar situaciones cotidianas",
      "Discutir las emociones expresadas",
    ],
    objectives: ["Desarrollar habilidades sociales", "Mejorar expresión emocional", "Fortalecer pragmática"],
    ageRange: "8-16 años",
    createdBy: "IA",
    tags: ["pragmática", "emociones", "teatro", "social"],
    createdAt: "2024-12-02",
  },
  {
    id: "3",
    title: "Construcción de Historias",
    description: "Ejercicio narrativo para desarrollar habilidades de secuenciación y estructura del discurso.",
    category: "Lenguaje",
    difficulty: "Fácil",
    duration: 20,
    materials: ["Imágenes secuenciales", "Papel", "Lápices de colores"],
    instructions: [
      "Mostrar secuencia de imágenes",
      "Identificar personajes y acciones",
      "Crear historia coherente",
      "Dibujar escena favorita",
    ],
    objectives: ["Desarrollar narrativa", "Mejorar secuenciación", "Ampliar vocabulario"],
    ageRange: "4-10 años",
    createdBy: "Manual",
    tags: ["narrativa", "secuenciación", "creatividad"],
    createdAt: "2024-12-03",
  },
]

export const references: Reference[] = [
  {
    id: "1",
    title: "Modelo de Intervención Fonológica Basado en Ciclos",
    year: 2020,
  },
  {
    id: "2",
    title: "Terapia de Fluidez: Enfoque Integral",
    year: 2019,
  },
  {
    id: "3",
    title: "Estimulación del Lenguaje en Edad Temprana",
    year: 2021,
  },
  {
    id: "4",
    title: "Intervención Pragmática en TEA",
    year: 2022,
  },
]

export const evaluationTools: EvaluationTool[] = [
  {
    id: "1",
    name: "Test para la Comprensión Auditiva del Lenguaje (TECAL)",
    type: "Estandarizada",
    area: "Lenguaje Comprensivo",
    description:
      "Evalúa la comprensión auditiva del lenguaje en niños de 3 a 6 años. Incluye comprensión de vocabulario, morfosintaxis y pragmática.",
    ageRange: "3-6 años",
    administrationTime: 30,
    materials: ["Manual", "Cuadernillo de láminas", "Protocolo de registro"],
  },
  {
    id: "2",
    name: "Test de Articulación a la Repetición (TAR)",
    type: "Estandarizada",
    area: "Articulación",
    description:
      "Evalúa la capacidad articulatoria mediante repetición de palabras y pseudopalabras. Identifica patrones de error fonológico.",
    ageRange: "3-7 años",
    administrationTime: 20,
    materials: ["Manual", "Tarjetas de estímulos", "Hoja de registro"],
  },
  {
    id: "3",
    name: "Evaluación Informal de Pragmática",
    type: "No Estandarizada",
    area: "Pragmática",
    description:
      "Observación estructurada de habilidades pragmáticas en contextos naturales de comunicación. Incluye turnos, coherencia y adecuación.",
    ageRange: "4-12 años",
    administrationTime: 45,
    materials: ["Pauta de observación", "Materiales lúdicos", "Grabadora"],
  },
  {
    id: "4",
    name: "Protocolo de Evaluación de Voz Infantil",
    type: "No Estandarizada",
    area: "Voz",
    description:
      "Evaluación perceptual y acústica de la voz en población pediátrica. Incluye análisis de calidad vocal y parámetros acústicos.",
    ageRange: "5-16 años",
    administrationTime: 40,
    materials: ["Software de análisis acústico", "Micrófono", "Protocolo perceptual"],
  },
  {
    id: "5",
    name: "Test de Fluidez Verbal Semántica",
    type: "Estandarizada",
    area: "Lenguaje Expresivo",
    description:
      "Evalúa la fluidez verbal mediante generación de palabras por categorías semánticas. Mide velocidad de procesamiento léxico.",
    ageRange: "6-16 años",
    administrationTime: 15,
    materials: ["Manual", "Cronómetro", "Hoja de registro"],
  },
  {
    id: "6",
    name: "Evaluación de Deglución Pediátrica",
    type: "No Estandarizada",
    area: "Deglución",
    description:
      "Protocolo de evaluación clínica de la deglución en niños. Incluye evaluación anatómica, funcional y de seguridad.",
    ageRange: "0-18 años",
    administrationTime: 60,
    materials: ["Alimentos de diferentes texturas", "Vaso con boquilla", "Linterna"],
  },
]
